#Site settings

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown

title: Always Free Résumé Builder
description: >-
  blah blah

#temporary until I get it complete
baseurl: ""
url: "https://dev.alwaysfreeresume.com"

# defaults:
#  -
#    scope:
#      path: ""
#        values:
#        layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - oldpages/